name: Analysis
on: [push, pull_request]
jobs:
  parallel-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer update --no-interaction --no-progress --prefer-dist --ansi
      - run: ./vendor/bin/parallel-lint --colors ./src ./tests
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer update --no-interaction --no-progress --prefer-dist --ansi
      - run: composer phpcs -- --colors
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf /tmp/phpstan
      - run: composer update --no-interaction --no-progress --prefer-dist --ansi
      - run: composer phpstan -- --no-progress --ansi
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run prettier -- --check
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run eslint -- --color
